add ER diagram
Shogoy0178/myapp pull request #3
Opened 2024-11-16 13:51 UTC by Shogoy0178

### ER図
![image](https://github.com/user-attachments/assets/1c2d7c91-c516-4d6c-9e2e-22cf2ec1920b)

### 本サービスの概要（700文字以内）
お気に入りの映画の楽曲を共有するサービスです。映画を見る楽しみの１つとして、音楽があります。オープニングやエンディング、クライマックスや何気ないシーンでも音楽が流れています。多くの人が、これまで見てきた映画に好きな音楽や思い入れのある音楽があるはずです。そのような音楽を知ってもらい、共感できるようなサービスです。自分のお気に入り楽曲を共有するだけでなく、新しい映画や音楽を発見することができます。映画と音楽を紐づけた投稿には、映画の予告編を閲覧できるようにし、見る映画に悩んでいる人も音楽を切り口に、見たい映画を探すことができます。

### MVPで実装する予定の機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] 記事投稿機能
- [x] 記事閲覧機能（未ログインでも閲覧可能）
- [x] 記事編集機能
- [x] 記事削除機能
- [x] コメント投稿機能
- [x] 検索機能
- [x] いいね機能
- [x] コメント投稿機能
- [x] マイページ機能
- [x] お問い合わせフォーム
- [x] 退会フォーム
- [x] パスワード再設定機能

### ER図の注意点
- [x] プルリクエストに最新のER図のスクリーンショットを画像が表示される形で掲載できているか？
- [x] テーブル名は複数形になっているか？
- [x] カラムの型は記載されているか？
- [x] 外部キーは適切に設けられているか？
- [x] リレーションは適切に描かれているか？多対多の関係は存在しないか？
- [x] カラムの型は記載されているか？
- [x] STIは使用しないER図になっているか？
- [x] Postsテーブルにpoast_nameのように"テーブル名+カラム名"を付けていないか？

2024-11-17 05:11 UTC, tarakish requested changes
確認しました。以下コメントです！

---

-  timestamps
  - created_at, updated_atは基本的に全てのテーブルに存在するため、全てに記載するorしないで統一しておきましょう！

- musics
  - こちらは1アルバム(=サントラ)を表すものか、1曲を表すものかどちらでしょうか？
    - 1曲の場合、postと1対多になっていますが、一つの映画に複数の音楽を紐づけることはしない想定でしょうか？
  - こちらは同じ楽曲であれば、ユーザーに関わらずすべて同じレコードを参照するのではなく、同じ楽曲であってもユーザーごとに違うレコードを参照する想定でしょうか？

- users
  - 認証に必要なカラムが足りているかどうかご確認をお願いします。

2024-11-17 09:39 UTC, Shogoy0178 commented
フィードバックありがとうございます。
以下、回答と修正内容になります。ご確認よろしくお願いいたします。

- timestamps
created_at, updated_atの記載を全て削除しました。
- musics
  - 1アルバムではなく、1曲です。「お気に入りの楽曲を共有する」をコンセプトとしているので、複数音楽の紐付けはできない仕様にします。
  - 同じ楽曲であれば、ユーザーに関わらず全て同じレコードを参照します。
 - users
 パスワードリセット機能に関するカラムをER図に追加しました。
 
 ER図
 
![image](https://github.com/user-attachments/assets/a812378a-4987-442e-98e6-7d5e66404274)

2024-11-18 02:41 UTC, tmtkzk0823 commented
修正、ご説明ありがとうございます。
以下、追加のコメントです.

---

### usersテーブル
- usernameカラムはnameのみでいいかと思いました。（テーブル名からuserの情報とわかるため）

###commentsテーブル
- bodyなど、「コメントの内容」が入るカラムが見受けられないのでご確認をお願いします。

### postsテーブル
- bodyなど、「投稿の内容」が入るカラムが見受けられないのですが、こちらはこの構成であっていますでしょうか？

2024-11-18 10:12 UTC, Shogoy0178 commented
フィードバックありがとうございます。
以下、回答と修正内容になります。よろしくお願いいたします。
- usersテーブルのusernameをnameに変更しました
- commentsテーブルにbodyを追加しました
- 投稿内容はpostsテーブルのbody(コメント内容)やmoviesテーブルの映画情報とmusicsテーブルの音楽情報から構成されるため、このままの仕様で実装することを考えています
  
ER図
![image](https://github.com/user-attachments/assets/77db36f0-3abb-49eb-9b03-a68ffd5afb93)

2024-11-19 03:04 UTC, TakenakaEri commented
LGTMです！

開発を進めていくうえで、修正が必要になる場面もあるかとお思います。」
その際は、ご自身の判断で適時修正して開発を進めて問題ありません。

次も頑張ってください！

2024-11-19 10:40 UTC, merged